### ISSUE TITLE
item loss from stash

### ISSUE THREAD

**Issue by imgabo** [qbcore-framework/qb-inventory#233] opened 2022-02-22 01:33 UTC
some items loss randomly from stash

**Comment by scrubh** [comment] 2022-03-01 05:09
This needs to be fixed, people on my server reporting it too, same happens with glove box

**Comment by ShomyTKD** [comment] 2022-03-17 09:04
I have reports for the same issue. My guess from what people are telling me is that their stash gets full and then for whatever reason it deletes a few items (doubt it has to do with weight since I increased it massively). I hope there will be some fix for this.

**Comment by restray** [comment] 2022-03-29 14:55
Can you help us reproducing this behavious ?
Were you able to reproduce it with the latest version of the qb-inventory ?

**Comment by ShomyTKD** [comment] 2022-03-29 16:42
Hey restray, I tried reproducing it but without any luck. It just happens randomly and not for all players. As mentioned above, every time I asked them what were they doing, they simply said that they were transferring items and that their stash was almost full. I am indeed using the latest version of qb-inventory.

**Comment by restray** [comment] 2022-03-29 16:46
No errors in the server logs, nothing in the client logs (F8) ?

I'll try to reproduce it but I still need some more informations about that issue

**Comment by xenfovn** [comment] 2022-03-30 05:50
I also had the same problem, it would repeat after restarting the server, not very often

**Comment by ShomyTKD** [comment] 2022-03-30 06:41
> No errors in the server logs, nothing in the client logs (F8) ?
> 
> I'll try to reproduce it but I still need some more informations about that issue

No errors, nothing.. I understand it's difficult to fix something when you don't know the cause, but sadly it's very random.. I had a situation yesterday where the guy lost 2000 baggies from his boss stash. He also mentioned that two pistols disappeared in front of him (he put them inside the stash, closed the stash and opened again and they were gone).

**Comment by restray** [comment] 2022-03-30 18:11
Thanks for your replies! I'm currently working on it, watch #256 to be updated when it's merged ;)

**Closed** 2022-04-09 14:24 UTC
Labels: bug, question
